### ISSUE TITLE
rounding.Ceil sometimes returns the floor rather than the ceiling

### ISSUE THREAD

**Issue by APILLSBURY** [wadey/go-rounding#1]
I expect the following line to evaluate to true:
`big.NewRat(1, 1).Cmp(rounding.Round(big.NewRat(1, 100), 0, rounding.Ceil)) == 0`

However, the result of `rounding.Round(big.NewRat(1, 100), 0, rounding.Ceil)` is actually 0 rather than 1. I believe this is due to the truncating logic [here](https://github.com/wadey/go-rounding/blob/693d3ce813446db15917c5f49a77d91f6037c2b9/round.go#L114).

Is this a bug or am I misunderstanding the intention of rounding.Ceil?

**Comment by wadey** [comment]
Wow yes, good catch. There is an issue with RoundUp, RoundCeil and RoundFloor for numbers that have a zero between where you want to round to and other digits. Working on a patch now.

**Comment by wadey** [comment]
I've created a fix here: https://github.com/wadey/go-rounding/pull/3

I'll go ahead and merge later today unless I hear any negative feedback.
