### ISSUE TITLE
Rounding up goes to x.9 rather than x+1

### ISSUE THREAD

**Issue by APILLSBURY** [wadey/go-rounding#4]
Your test code was masking this issue by only comparing float strings at the same precision you were trying to round to. If you change `testRounding` to be the following, tests break:
```
func testRounding(t *testing.T, a, b string, prec int, method RoundingMode) {
	x, ok := new(big.Rat).SetString(a)
	if !ok {
		t.Fatalf("Failed to parse: %s", a)
	}
	Round(x, prec, method)
	r := x.FloatString(prec + 1)
	y, ok := new(big.Rat).SetString(b)
	if !ok {
		t.Fatalf("Failed to parse: %s", b)
	}
	if r != y.FloatString(prec+1) {
		t.Errorf("test Round(%v, %v, %v) == %s. Got %v", a, prec, method, b, r)
	}
}
```

**Comment by wadey** [comment]
Whoops that is embarrassing. I see the issue and will push a fix when I am back to my computer later today.

**Comment by wadey** [comment]
Fixed the tests by not using FloatString at all and comparing the Rationals directly:

- https://github.com/wadey/go-rounding/commit/118f0f41c03410408a3bbde8547cb24fb5eb613f

**Comment by wadey** [comment]
Fixed the issue by removing special case code I had added that was incorrect:

- https://github.com/wadey/go-rounding/commit/ec97eb65ad4be9192c76c510e1abf255fa26c918

Thanks for reporting.
